# Generated by Django 5.1.1 on 2024-10-27 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssistantBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssistantBackend.conversation')),
            ],
            options={
                'db_table': 'conversation_details',
            },
        ),
        migrations.CreateModel(
            name='DocumentDetail',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssistantBackend.conversationdetail')),
            ],
            options={
                'db_table': 'document_details',
            },
        ),
        migrations.CreateModel(
            name='GenerationDetail',
            fields=[
                ('generation_id', models.AutoField(primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=True)),
                ('done_reason', models.CharField(choices=[('stop', 'Stop'), ('complete', 'Complete')], default='stop', max_length=10)),
                ('total_duration', models.BigIntegerField(blank=True, null=True)),
                ('load_duration', models.BigIntegerField(blank=True, null=True)),
                ('prompt_eval_count', models.IntegerField(blank=True, null=True)),
                ('prompt_eval_duration', models.BigIntegerField(blank=True, null=True)),
                ('eval_count', models.IntegerField(blank=True, null=True)),
                ('eval_duration', models.BigIntegerField(blank=True, null=True)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssistantBackend.conversationdetail')),
            ],
            options={
                'db_table': 'generation_details',
            },
        ),
        migrations.DeleteModel(
            name='Student1',
        ),
    ]
